repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [ python ]

      - id: pytest
        name: pytest
        stages: [ commit ]
        types: [ python ]
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
