"""Update title & artist size

Revision ID: 14c9053b46b7
Revises: 33812076d563
Create Date: 2022-07-11 01:33:21.030014

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '14c9053b46b7'
down_revision = '33812076d563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tracks', 'artist',
        existing_type=sa.String(length=50),
        type_=sa.String(length=100),
        existing_nullable=False
    )
    op.alter_column(
        'tracks', 'title',
        existing_type=sa.String(length=50),
        type_=sa.String(length=100),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tracks', 'artist',
        existing_type=sa.String(length=100),
        type_=sa.String(length=50),
        existing_nullable=False
    )
    op.alter_column(
        'tracks', 'title',
        existing_type=sa.String(length=100),
        type_=sa.String(length=50),
        existing_nullable=False
    )
    # ### end Alembic commands ###
