"""Update tracks new column duration

Revision ID: 2021c54e4187
Revises: 9c3ebd311352
Create Date: 2022-07-18 12:36:24.913938

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2021c54e4187'
down_revision = '9c3ebd311352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('duration', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'duration')
    # ### end Alembic commands ###
