"""Update url and cover_url size

Revision ID: 33812076d563
Revises: 4ca2de91a793
Create Date: 2022-07-08 23:19:00.710722

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '33812076d563'
down_revision = '4ca2de91a793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tracks', 'url',
        existing_type=sa.String(length=150),
        type_=sa.String(length=250),
        existing_nullable=False
    )
    op.alter_column(
        'tracks', 'cover_url',
        existing_type=sa.String(length=150),
        type_=sa.String(length=250),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tracks', 'url',
        existing_type=sa.String(length=250),
        type_=sa.String(length=150),
        existing_nullable=False
    )
    op.alter_column(
        'tracks', 'cover_url',
        existing_type=sa.String(length=250),
        type_=sa.String(length=150),
        existing_nullable=False
    )
    # ### end Alembic commands ###
