"""Initial

Revision ID: 4ca2de91a793
Revises: 
Create Date: 2022-07-06 14:04:21.379596

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4ca2de91a793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tracks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_id', sa.String(length=100), nullable=True),
        sa.Column('artist', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('url', sa.String(length=150), nullable=False),
        sa.Column('cover_url', sa.String(length=150), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pktracks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###
