"""New table Users

Revision ID: 9c3ebd311352
Revises: 14c9053b46b7
Create Date: 2022-07-15 13:12:09.249201

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9c3ebd311352'
down_revision = '14c9053b46b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('vk_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pkusers'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
